from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from rest_framework_mongoengine import routers

from app.viewsets import QuestionnaireViewSet, PetitionViewSet, UserViewSet,\
    UserViewSetById, AMIViewSet

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'questionnaire', QuestionnaireViewSet, r"questionnaire")
router.register(r'petition', PetitionViewSet, r"petition")
router.register(r'user', UserViewSet, r"user")
router.register(r'user_id', UserViewSetById, r"user_id")
router.register(r'ami', AMIViewSet, r"ami")

urlpatterns = [
    # default django admin interface
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', TemplateView.as_view(template_name='control_panel.html')),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    # REST API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),
]

